<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_I understand</name>
   <tag></tag>
   <elementGuidId>feae1c69-9fa6-4ca1-9417-dd3afb54a77d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.button.button-blue</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;I understand&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c0f7f6f8-fda0-4f88-990b-ceeddbb0212a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>96df0ad1-4fee-4e01-9166-07defa1835dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button-blue</value>
      <webElementGuid>c0609985-3e52-4fbc-beac-88430c34fc8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I understand </value>
      <webElementGuid>faccd4ff-e761-455b-9f01-a77be7c75dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;modal-mask risk-disclosure-modal-modal&quot;]/div[@class=&quot;modal-wrapper&quot;]/div[@class=&quot;modal-container layer-2&quot;]/div[@class=&quot;modal-footer&quot;]/div[@class=&quot;actions&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;tweleve columns text-right&quot;]/button[@class=&quot;button button-blue&quot;]</value>
      <webElementGuid>1138ec2b-2a5a-459f-8d9e-ab6556a1deb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>b0b72a8c-3eb7-4307-9b7a-558797e633a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[6]/div/div/div[3]/div/div/div/button</value>
      <webElementGuid>dba7cd37-75a1-46a3-88d6-2aecf2e1dfa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SEBI study'])[1]/following::button[1]</value>
      <webElementGuid>8c6ff2fe-a33a-4f39-bc14-8e7d4c327df6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Those making net trading profits, incurred between 15% to 50% of such profits as transaction cost.'])[1]/following::button[1]</value>
      <webElementGuid>18f2d2e6-b259-4e8d-9c68-8c6579320081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='I understand']/parent::*</value>
      <webElementGuid>996ade84-5b38-40c6-a20e-5ff59d8d1329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/button</value>
      <webElementGuid>dff71328-2f1e-46be-82aa-8d7f7952d8e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'I understand ' or . = 'I understand ')]</value>
      <webElementGuid>6dcfaaef-5438-4009-8f8c-cdc5c9b22a35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
