<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_2,904.51</name>
   <tag></tag>
   <elementGuidId>6a79bb18-08f6-4f05-a142-0ca731f04e7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/div/div/div/section/div/div/div/h4</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h4.value.text-bold.text-pagetitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;2,904.51&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>ea5a12e0-a431-4195-a9d8-354bfd94a93c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>value text-bold text-pagetitle</value>
      <webElementGuid>6cb9e605-7298-44d4-93fe-7f06390eb453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2,904.51</value>
      <webElementGuid>a5b392c2-c100-4027-ad06-8e8e888562f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;container wrapper&quot;]/div[@class=&quot;container-right&quot;]/div[@class=&quot;page-content holdings&quot;]/div[@class=&quot;holdings&quot;]/section[@class=&quot;holdings-table table-wrapper&quot;]/div[@class=&quot;cards&quot;]/div[@class=&quot;stats row&quot;]/div[@class=&quot;three columns&quot;]/h4[@class=&quot;value text-bold text-pagetitle&quot;]</value>
      <webElementGuid>ad98986b-f160-4570-8957-1b775d7a7494</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/div/div/section/div/div/div/h4</value>
      <webElementGuid>0c8f97c7-82b6-4aaf-a390-e979561452ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total investment'])[1]/following::h4[1]</value>
      <webElementGuid>6d73d800-6296-4a6c-b5c7-164198a3da4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(7)'])[1]/following::h4[1]</value>
      <webElementGuid>0bde5596-07e6-4df1-9d5e-c6f26af4643d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current value'])[1]/preceding::h4[1]</value>
      <webElementGuid>fc3e39cf-10eb-45cf-88b2-621c736c8f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2,904']/parent::*</value>
      <webElementGuid>ca10ed81-26f1-442f-8b7b-6578d11fe31f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>6fd50f0b-3a78-4447-bf9c-68598104fcaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = '2,904.51' or . = '2,904.51')]</value>
      <webElementGuid>63c6bc5e-91b6-4548-a6d4-388ab763c106</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
